### ISSUE TITLE
更改Document文件夹的默认路径会导致安装失败

### ISSUE THREAD

**Issue by teivosic** [inkitter/HOI4_mod#1]
``` bat
mklink /j "%USERPROFILE%\Documents\Paradox Interactive\Hearts of Iron IV\mod\_Inkitmod" _Inkitmod
```

无论如何会定位到c盘的默认路径

已下是我手动更改的定位

``` bat
set USERPROFILE=E:
mklink /j "%USERPROFILE%\Documents\Paradox Interactive\Hearts of Iron IV\mod\_Inkitmod" _Inkitmod
```

Documents路径是通过win10默认方法移动的

**Comment by teivosic** [comment]
默认的unix的换行直接运行会报错，估计是我的个人问题
需要手动更改为windows的换行
系统win10 14352

**Comment by inkitter** [comment]
@teivosic 这个问题似乎有点难办，查了半天获取到的定位方式，发现还是只能靠 %USERPROFILE%。。。但是它无法指向修改过的 我的文档 目录。

**Comment by inkitter** [comment]
@teivosic 
已经加入查询注册表的指令来确定 我的文档 位置。
`FOR /F "tokens=3* delims= " %%a in ('reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v "Personal"') do (set mydoc=%%a)`
之后使用 `%mydoc%` 来调用
